# Rails helper for displaying footprint data.
module TronprintHelper

  # The total amount of CO2e generated by the application.
  def total_footprint
    Tronprint.statistics.total_footprint
  end

  # The total amount of electricity used by the application.
  def total_electricity
    Tronprint.statistics.total_electricity
  end

  # A URL for the methodology statement of the emissions calculation.
  def footprint_methodology
    Tronprint.statistics.total_footprint_methodology
  end

  # Let the world know that your app is powered by CM1
  def cm1_badge
    %q{<script type="text/javascript" src="http://carbon.brighterplanet.com/badge.js"></script>}.
      html_safe
  end
end
